### ISSUE TITLE
Invite for collaboration work

### ISSUE THREAD

**Issue by douglascrp** [rmberg/alfresco-s3-adapter#3]
Hello @rmberg 

I have just found your project, and I saw you took the same path as I did before which was migrating the old google code project into github and made changes.
You can check my project here https://github.com/douglascrp/alfresco-cloud-store

The reason for this issue is to invite you to merge both projects and try to work on just one solution that the community could use.

Let me know if you are interested on this.

Regards.

**Comment by rmberg** [comment]
Hi @douglascrp, I'm not really maintaining this repo anymore, it was just an experiment. If you'd like to merge this into your repo, let me know, and then I'll just depricate this one.

**Comment by douglascrp** [comment]
Sorry for the late response, but yes, that would be nice to do.
Unfortunately I do not have the time right now.

Lets keep them as they are right now, and when I am available, I will review all the changes you have done and decide what to do.
I also have some feedback from some guys that tried it before, and I think those problems have to be solved in order to have a ready to use addon.

Thank you for now, and I hope to be able to get back to this project soon.

**Comment by rwiffin** [comment]
Hi @douglascrp. I have been looking at this project and have downloaded, upped the api version to 2.2 and have been testing against S3. I would be interested to understand what other issues you have seen from your side - or those of your colleagues that have tried this before.

**Comment by rwiffin** [comment]
As a point of note: The Alfresco standard integration with S3 uses the jets3t API rather than the S3 Java SDK. My research indicates that the S3JSDK is the most reliable and best maintained, although I have been using the jets3t connector in other situations and this seems to work fine.

**Comment by douglascrp** [comment]
@rwiffin 
This is the issue I have just created to register the feedback 
https://github.com/douglascrp/alfresco-cloud-store/issues/11

**Comment by marsv024** [comment]
FYI I've created a fork as well and updated to sdk 3 and the latest aws api. I've gone with the approach that the module needs more configuration to actually do something to allow to use it in different scenarios, not only as a main content store. 

I found one issue which was that the s3 writing was not transactionally safe. It was done in the background in the original code which in case something got interrupted you could end up with corrupt data. This is now fixed in my code and we always wait for the upload to finish before allowing the transaction to finish.

**Comment by rmberg** [comment]
@marsv024 & @douglascrp I'm going to mark this repo as depricated/no longer maintained and place a link to your repos in the readme as suitable alternatives.
